config/routes.rb
Rails.application.routes.draw do
  get 'patterns/view'

  get '/courses/autocomplete' => 'courses#autocomplete'

  get '/calendar' => 'calendar#index'

  get '/notifications/list' => 'notifications#list'

  resources :courses
  resources :requests

  devise_for :users
  resources :users, only: %w(index show edit update) do
    resources :attributions, only: %w(new create edit update)
  end

  root to: 'courses#index'

  post '/courses/:id/enroll' => 'courses#enroll'
  post '/courses/:id/withdraw' => 'courses#withdraw'
  get '/geo_scope_courses' => 'courses#geo_scope_courses'
  get '/notifications/:id/see' => 'notifications#see'

end

app/models/request.rb
class Request < ActiveRecord::Base
  include Locatable

  has_and_belongs_to_many :tags
  belongs_to :requester, class_name: 'User'
  belongs_to :location

  validates :location, presence: true, allow_blank: false
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  include Taggable
  include Geolocation


  before_action :set_request, only: [:edit, :update, :destroy]
  before_action :require_eligible, only: [:edit, :update, :destroy]
  before_action :require_login, only: [:new]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
    @tags = Tag.uniq.pluck(:label)
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @tags = Tag.uniq.pluck(:label)
    @filtered_tags = Tag.where(label: params[:id])

    @requests = []
    @filtered_tags.each do |tag|
      @requests += Request.joins(:tags).where("tags.id = :tag_id", {tag_id: tag.id}).to_a
    end

    @requests.uniq! { |r| r.id }

    render 'index'
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    location = request_params[:location]
    @request = Request.new(request_params.merge(requester: current_user, location: geocode_location(location)))

    respond_to do |format|
      if @request.save
        @request.tags << extract_tags(params[:request][:tags])
        format.html { redirect_to :root, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    location = request_params[:location]

    if @request.update(request_params.merge(location: geocode_location(location)))
      @request.tags << extract_tags(params[:request][:tags])
      format.html { redirect_to @request, notice: 'Request was successfully updated.' }
      format.json { render :show, status: :ok, location: @request }
    else
      format.html { render :edit }
      format.json { render json: @request.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    def require_eligible
      unless current_user && (current_user.admin? || current_user == @course.lecturer)
        redirect_to @course
      end
    end

    def require_login
      redirect_to new_user_session_path unless current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :date, :location, :description)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for @request, :html => {:role => 'form', :class => 'form-horizontal col-sm-6 col-sm-offset-3'} do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tags %><br>
    <%= f.text_field :tags, :value => @request.tags.map(&:label).join, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<div class="page-header">
  <h1>Edit course request</h1>
</div>

<%= render 'form' %>

app/views/requests/index.html.erb
<div class="row">
  <div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
      <% @tags.each do |tag| %>
        <li><%= link_to tag, '/requests/' + tag %></li>
      <% end %>
    </ul>
  </div>

  <div id="js-requests-list" class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <%= render 'courses/tags', {requests: @requests} %>
  </div>
</div>

app/views/requests/new.html.erb
<div class="page-header">
  <h1>New course request</h1>
</div>

<%= render 'form' %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @request.location %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @request.tags.map(&:label).join ', ' %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/requests/update.html.erb
<h1>Requests#update</h1>
<p>Find me in app/views/requests/update.html.erb</p>