config/routes.rb
Rails.application.routes.draw do
  get 'patterns/view'

  get '/courses/autocomplete' => 'courses#autocomplete'

  get '/calendar' => 'calendar#index'

  get '/notifications/list' => 'notifications#list'

  resources :courses
  resources :requests

  devise_for :users
  resources :users, only: %w(index show edit update) do
    resources :attributions, only: %w(new create edit update)
  end

  root to: 'courses#index'

  post '/courses/:id/enroll' => 'courses#enroll'
  post '/courses/:id/withdraw' => 'courses#withdraw'
  get '/geo_scope_courses' => 'courses#geo_scope_courses'
  get '/notifications/:id/see' => 'notifications#see'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Crashcourse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style>
    html, body {
        height: 100%;
    }
    .wrapper {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        margin: 0 auto -63px;
    }
    .push {
        height: 63px;
    }
    /* not required for sticky footer; just pushes hero down a bit */
    .wrapper > .container {
    }
    .thumbnail {
      border: 0;
    }
    .popover {
      width: 220px ! important;
    }
  </style>
  <style type="text/css">
 .bs-example{
   font-family: sans-serif;
   position: relative;
   margin: 100px;
 }
 .typeahead, .tt-query, .tt-hint {
   border: 1px solid #CCCCCC;
   border-radius: 8px;
   font-size: 18px;
   height: 30px;
   line-height: 30px;
   outline: medium none;
   padding:21px;
   width: 396px;
 }
 .typeahead {
   background-color: #FFFFFF;
 }
 .typeahead:focus {
   border: 2px solid #0097CF;
 }
 .tt-query {
   box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
 }
 .tt-hint {
   color: #999999;
 }
 .tt-dropdown-menu {
   background-color: #FFFFFF;
   border: 1px solid rgba(0, 0, 0, 0.2);
   border-radius: 8px;
   box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
   margin-top: 12px;
   padding: 8px 0;
   width: 100%;
 }
 .tt-suggestion {
   font-size: 24px;
   line-height: 24px;
   padding: 3px 20px;
 }
 .tt-suggestion.tt-is-under-cursor {
   background-color: #0097CF;
   color: #FFFFFF;
 }
 .tt-suggestion p {
   margin: 0;
 }


/*
 * Global add-ons
 */
.sub-header {
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}

/* Hide for mobile, show later */
.sidebar {
  display: none;
}
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 51px;
    bottom: 0;
    left: 0;
    z-index: 1000;
    display: block;
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
    background-color: #f5f5f5;
    border-right: 1px solid #eee;
  }
}

/* Sidebar navigation */
.nav-sidebar {
  margin-right: -21px; /* 20px padding + 1px border */
  margin-bottom: 20px;
  margin-left: -20px;
}
.nav-sidebar > li > a {
  padding-right: 20px;
  padding-left: 20px;
}
.nav-sidebar > .active > a {
  color: #fff;
  background-color: #428bca;
}


/*
 * Main content
 */
.main {
  padding: 20px;
}
@media (min-width: 768px) {
  .main {
    padding-right: 40px;
    padding-left: 40px;
  }
}
.main .page-header {
  margin-top: 0;
}


/*
 * Placeholder dashboard ideas
 */
.placeholders {
  margin-bottom: 30px;
  text-align: center;
}
.placeholders h4 {
  margin-bottom: 0;
}
.placeholder {
  margin-bottom: 20px;
}
.placeholder img {
  display: inline-block;
  border-radius: 50%;
}
 </style>


<script type="text/javascript">
  $(document).bind('page:change', function() {
    Holder.run();
  });
</script>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Courses</a>
        </div>
        <div class="navbar-header">
          <%= link_to 'Requests', requests_path, :class => 'navbar-brand' %>
        </div>
        <div class="navbar-header">
          <%= link_to 'Activity', patterns_view_path, :class => 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li>
            <%= link_to 'My Calendar', calendar_path %>
          </li>
          <li>
            <%= link_to 'New Course', new_course_path %>
          </li>
          <li>
            <%= link_to 'New Request', new_request_path %>
          </li>
          <li>
            <%= link_to current_user do %>
              Howdy, <%= current_user.first_name %>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li><a id="toggle_notifications" href="#" data-ajaxload="/notifications/list" data-no-turbolink="true">
              <% if @has_notifications %>
                <span class="badge alert-danger">&nbsp;</span>
              <% else %>
                <span class="badge alert-default">&nbsp;</span>
              <% end %>
            </a></li>
          <% end %>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="wrapper">
      <div class="container">
        <%= yield %>
      </div> <!-- /container -->
      <div class="push"><!--//--></div>
    </div>
    <hr>

    <footer>
      <div class="container">
        <p>&copy; Some rights reserved 2014</p>
      </div>
    </footer>
</body>
</html>